# -*- coding: utf-8 -*-
"""Make_square.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/rdestenay/oldpicsrestoration/blob/master/Make_square.ipynb
"""

from PIL import Image
import glob
from os import path

def resize_square(im, desired_size):
    old_size = im.size  # old_size[0] is in (width, height) format
    ratio = float(desired_size)/min(old_size)
    new_size = tuple([int(x*ratio) for x in old_size])
    im = im.resize(new_size)
    # create a new image and paste the resized on it
    new_im = Image.new("RGB", (desired_size, desired_size))
    new_im.paste(im, ((desired_size-new_size[0])//2,
                        (desired_size-new_size[1])//2))
    return new_im

image_list = []
for filename in glob.glob('color/*.jpg'):
    im=Image.open(filename)
    im = resize_square(im, 512)
    im.save("color_square/"+path.basename(filename))

